### ISSUE TITLE
Adding Contributing Guidelines

### ISSUE THREAD

**Issue by italobusi** [younglee-ietf/ietf-optical-impairment-yang#11]
I think it would be useful/clear adding contributing guidelines highlighting that all the material in this repository is considered a contribution to IETF Standards Process

See for example: https://github.com/martinthomson/i-d-template/blob/master/template/CONTRIBUTING.md

Proposed changes: https://github.com/italobusi/ietf-optical-impairment-yang-contribute

If you are ok, I will submit a pull request

**Comment by dieterbeller** [comment]
I support the proposed changes.

**Comment by egriseri** [comment]
I support as well.

**Comment by younglee-ietf** [comment]
I support this proposal. Please submit a pull request.

**Comment by sergiobelotti** [comment]
I support this proposal. Please submit a pull request.

**Comment by italobusi** [comment]
Created: pull request #13

**Comment by dieterbeller** [comment]
2019-05-28: Proposed changes merged into master branch.
