### ISSUE TITLE
pyang error in ietf-optical-impairment-topology.yang

### ISSUE THREAD

**Issue by dieterbeller** [younglee-ietf/ietf-optical-impairment-yang#6]
File references:
* ietf-optical-impairment-topology.yang: https://github.com/younglee-ietf/ietf-optical-impairment-yang/commit/02fbe12d754464bf6dd1685497fec393868c03e1
* ietf-layer0-types.yang: https://github.com/younglee-ietf/ietf-optical-impairment-yang/commit/2fb5e2c088b17b1b7758ffdd3c8baf4ac3d6041b

pyang output :
```
Line 847 (at C:\Users\beller\OneDrive - Nokia\Standardization\IETF\CCAMP\L0-topology\L0 topology all YANG modules\ietf-optical-impairment-topology.yang:749): error: the key "flex-n" does not reference an existing leaf
Line 752: error: grouping "flex-grid-channel" not found in module ietf-layer0-types
```

**Comment by younglee-ietf** [comment]
Yes, when we updated layer0-types file to globally change from flex to flexi, we should've updated ietf-optical-impairment-topology.yang files as well.
